openapi: 3.0.0
info:
  title: Products API
  description: API for managing products
  version: "1.0"
servers:
  - url: http://localhost:8000/api

paths:
  /products:
    get:
      tags:
        - Products
      summary: Get all products
      responses:
        '200':
          description: Products retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Mongo Object ID
                        title:
                          type: string
                        description:
                          type: string
                        price:
                          type: number
    post:
      tags:
        - Products
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                count:
                  type: string
      responses:
        '201':
          description: Product successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Mongo Object ID
                      title:
                        type: string
                      description:
                        type: string
                      price:
                        type: number
  /products/{id}:
    get:
      tags:
        - Products
      summary: Retrieve a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Mongo Object ID
      responses:
        '200':
          description: Product retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Mongo Object ID
                      title:
                        type: string
                      description:
                        type: string
                      price:
                        type: number
        '404':
          description: Products not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Products not found'
    put:
      tags:
        - Products
      summary: Update product details by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Mongo Object ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                count:
                  type: string
      responses:
        '200':
          description: Product information updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Mongo Object ID
                      title:
                        type: string
                      description:
                        type: string
                      price:
                        type: number
        '404':
          description: Products not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Products not found'
    delete:
      security:
        - bearerAuth: []
      tags:
        - Products
      summary: Delete a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: header
          name: is-admin
          required: true
          schema:
            type: boolean
      responses:
        '200':
          description: Product deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Mongo Object ID
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Unauthorized access'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Access denied'
        '404':
          description: Products not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Products not found'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT